-- =========================================================
-- Phase 3: admin audit logs
-- Requires:
--   - 20260325_init.sql
--   - 20260409_phase2_returned_enum.sql
--   - 20260409_phase2_returned_workflow.sql
-- Optional but recommended before this migration:
--   - 20260415_phase3_admin_permission_review.sql
-- Purpose:
--   - Record admin-side operations
--   - Track user invite, role changes, department changes
--   - Track request_types create / rename / delete
-- =========================================================

begin;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete restrict,
  action text not null,
  target_user_id uuid null references public.profiles(id) on delete set null,
  entity_type text not null,
  entity_id text null,
  before_data jsonb null,
  after_data jsonb null,
  created_at timestamptz not null default now()
);

comment on table public.admin_audit_logs is 'Audit logs for admin-side operations';
comment on column public.admin_audit_logs.action is 'INVITE_USER / UPDATE_USER_ROLE / UPDATE_USER_DEPARTMENT / CREATE_REQUEST_TYPE / RENAME_REQUEST_TYPE / DELETE_REQUEST_TYPE';
comment on column public.admin_audit_logs.entity_type is 'profiles / request_types / auth.users etc';

alter table public.admin_audit_logs enable row level security;

drop policy if exists "admin_audit_logs_admin_read" on public.admin_audit_logs;
create policy "admin_audit_logs_admin_read"
on public.admin_audit_logs
for select
using (public.current_role() = 'ADMIN');

drop policy if exists "admin_audit_logs_no_direct_write" on public.admin_audit_logs;
create policy "admin_audit_logs_no_direct_write"
on public.admin_audit_logs
for insert
with check (false);

commit;